version: 2
jobs:
  build:
    working_directory: /go/src/github.com/mattn/dboxpaper
    docker:
      - image: circleci/golang:1.13.7
 steps:
      - checkout
      - run: go get ./...
      - run: go test -v ./...
